### ISSUE TITLE
connection_lost doesn't seem to work

### ISSUE THREAD

**Issue by adongy** [gawel/irc3#117]
https://github.com/gawel/irc3/blob/master/irc3/__init__.py#L63-L71

If you trigger connection_lost, self.closed is set to True, then it calls close which immediately returns (since we just set closed to True)

Single threaded nature of python should be enough to guarantee that closed is set to True at the end of protocol.close(), so this line is not needed probably ?

https://github.com/gawel/irc3/blob/master/irc3/__init__.py#L64

**Comment by gawel** [comment]
I admit that I don't really know. This is poorly tested and require to be tested manually. As I remember this is like that because you do not need to close the transport when connection_lost is triggered. But I'm not really sure. Don't really know if unit tests can be improve on this part. May be hard....

**Comment by gawel** [comment]
Looks like you were right. Test added / line removed. Thanks

See https://github.com/gawel/irc3/commit/487c479ed1c9ff7578b88319a1d3c2c04db85d39
