### ISSUE TITLE
Channels is not populated on first join

### ISSUE THREAD

**Issue by kevinpostal** [gawel/irc3#159]
I used  `@irc3.event(irc3.rfc.JOIN)` and attempted to grab all the users permissions on first join.

It appears there is not way to view the details of `self.bot.channels` until a new user joins.

**Comment by gawel** [comment]
You mean when using the userlist plugin ? That's weird, because it catch RPL_NAMEREPLY https://github.com/gawel/irc3/blob/master/irc3/plugins/userlist.py#L155 And those are triggered by the server when the bot join.

**Comment by gawel** [comment]
Hm, so that's not a bug. Just realized that the name reply is triggered *after* join. There's no way to get the userlist of the channel on the first join event. So you may want to use https://irc3.readthedocs.io/en/latest/rfc.html#rpl-endofnames instead of join. You can combine both events with two `@event()` on the same function.

**Comment by kevinpostal** [comment]
Thanks!
