### ISSUE TITLE
Ability to reload plugins on the fly

### ISSUE THREAD

**Issue by metathink** [gawel/irc3#39]
It would be usefull when developing a plugin to be able to reload a specific plugin or all the plugins on the fly. I'm not sure where that new function should be available, maybe in the IrcBot instance or in a new plugin. A way to detect the reload of a plugin must also be provided, maybe a simple "before_reload" or "on_unload" method on the plugin's instance should be called.

Some servers don't like a lot of reconnection in a short period of time and this also would be usefull to make littles changes in a plugin while keeping the entire bot available for the users in the channel.

**Comment by pypingou** [comment]
Might be an idea: https://pypi.python.org/pypi/stevedore

**Comment by gawel** [comment]
reload mean 2 things for me:

- use new config values

- reload python code

The first one might be easy (with help of the storage plugin)

The second one is harder. Don't know if you can keep the connection while restarting a process. It will also require to keep a "state" like channel joins an users on channel (i'm thinking of the userlist plugin)

**Comment by pypingou** [comment]
I think people would not mind if the bot becomes unresponsive during the reload.
If it is fast enough (and that will depend of the plugin itself), the reload can probably be done without losing the connection to the irc server.

**Comment by gawel** [comment]
I came with this conclusion: there is no easy way to do that :)

What is ideally needed:
- keep a state of data you don't want to lose (userlist)
- keep track of asyncio.Handle you don't want to loose
- delete all registered events
- reload python code
- instanciate new plugins
- rescan events and commands

It's not possible to pickle plugins to get a current state mostly because handle objects (self.handle = loop.call_later()) are not pickable

So here is a solution: Plugins with a specific class method like PluginClass.reload(old_instance) can be reloaded. Then:

- the python code is reloaded
- for each plugins, we get the new plugin class and PluginClass.reload(old_instance) must return a ready to use instance of the plugin using old_instance if needed:
```
class UserList:

    @classmethod
    def reload(cls, old):
        new = cls(old.bot)
        new.userlist = old.userlist
        return new
```
- all events are removed from the registered events
- we rescan modules to load new commands / events / others using venusian
- everything should be fine without losing any incoming data

Thoughts ?

**Comment by metathink** [comment]
Everything sounds good to me. Also, if there is no chance that a plugin takes something else than the "bot" argument at the initialisation, we could even do:

```python
@classmethod
def reload(cls, old, new):
    new.userlist = old.userlist
    # ...
```

**Comment by gawel** [comment]
It's done.

Here the interface:

```python
class Plugin:
    def before_reload(self):
        pass
    def after_reload(self):
        pass
    @classmethod
    def reload(self, old):
        return cls(old.bot, argsifyouwant...)
```

All plugins are notified of before_reload/after_reload events. Only plugins with a reload method are reloaded

you can use bot.reload() or bot.reload(module,...) I guess a command can be added for that as a plugin. For now you can send a kill -HUP to the bot process.

As a bonus, bot.config is also reloaded so you can use after_reload to check/use new values
